[pytest]
markers =
    unit
    smoke

;; ReportPortal config
rp_endpoint = https://report-portal.nrao.casa
rp_project = dummy_app
rp_launch = 'Dummy App'
rp_launch_attributes = 'pytest'
rp_ignore_attributes = 'xfail' 'usefixture'
rp_verify_ssl = False
rp_launch_uuid_print = True
rp_api_retries = 2
; rp_mode = DEFAULT
