## sampleVar is the value that the app will pull from its environment to display on the webpage
sampleVar: default Helm value

## color is the color to use for the webpage background. Valid values are the Solarized colors: https://ethanschoonover.com/solarized/
color: yellow

## contextPath is the deployment path for the app
contextPath: "/"

replicaCount: 1

image:
  repository: "ghcr.io/nrao/releng/dummy_app"
  pullPolicy: IfNotPresent
  tag: "1.1.5"

tests:
  enabled: false
  ## Testing image
  # image:
  #   repository: "ghcr.io/nrao/releng/dummy_app/tests"
  #   pullPolicy: IfNotPresent
  #   tag: edge

## For simple usage, you can set single image pull credentials directly:
imageCredentials: {}
  ## for GHCR, username and password will need to be a valid GitHub user and token with package:read permissions, e.g:
  # registry: ghcr.io
  # username: someone
  # password: token

## alternatively, set imagePullSecrets (the dockerconfigjson Secret must then be created manually)
imagePullSecrets: []

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       pathType: ImplementationSpecific
  tls: []

resources: {}
