{{- if .Values.tests.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: '{{ include "dummyapp.fullname" . }}-smoke'
  labels:
    {{- include "dummyapp.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  template:
    metadata:
      labels:
        app: {{ include "dummyapp.fullname" . }}
        {{- include "dummyapp.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      {{- with .Values.imagePullSecrets }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.imageCredentials.password }}
        - name: '{{ include "dummyapp.fullname" . }}-registrykey'
      {{- end }}
      containers:
        - name: smoke-test
          image: '{{ .Values.tests.image.repository }}:{{ .Values.tests.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: {{ .Values.tests.image.pullPolicy }}
          env:
            - name: TEST_BASE_URL
              value: 'http://{{ include "dummyapp.fullname" . }}{{ .Values.contextPath | trimSuffix "/"}}'
          args:
            - smoke

      restartPolicy: Never
  backoffLimit: 1
  activeDeadlineSeconds: 120
{{- end }}
