name : Unit Test
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    
    - uses: ./.github/actions/setup-python
 
    - name: Install project dependencies
      shell: bash
      run: |
        python -m pip install --root-user-action=ignore --upgrade pip
        pip install --root-user-action=ignore -e . --group test

    - name: Unit test with coverage
      env:
        RP_API_KEY: ${{ secrets.REPORTPORTAL_API_KEY }}
      run: |
        pytest --junitxml=junit/test-results.xml \
          --cov=dummy_app --cov-report=xml \
          --rp-launch "$GITHUB_REF_NAME" \
          --rp-launch-description "${GITHUB_EVENT_NAME}: $GITHUB_REF_NAME | $GITHUB_SHA" \
          -o "rp_tests_attributes=unit github $GITHUB_ACTOR" \
          tests/unit/

    - name: Upload test results
      if: ${{ !env.ACT && always() }}
      uses: actions/upload-artifact@v7
      with:
        name: pytest-results
        path: junit/test-results.xml

    - name: Upload coverage results
      if: ${{ !env.ACT && always() }}
      uses: actions/upload-artifact@v7
      with:
        name: coverage-results
        path: coverage.xml
