name : Unit Test
on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'pyproject.toml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  prep_env:
    uses: $/.github/workflows/prep-env.yml

  unit:
    name : 'Unit tests'
    needs: [prep_env]
    runs-on: ubuntu-latest
    ## Replace with the following to run in cluster:
    # runs-on: 
    #   group: aws-arc
    #   labels: aws-arc-runner-lapis-dev
    # container:
    #   image: ubuntu:latest

    steps:
    ## Only necessary if runing on arc-runner
    # - name: install git
    #   run: |
    #     apt-get update
    #     apt-get install -y git libsqlite3-dev

    - uses: actions/checkout@v7
      with:
        ref:  ${{ github.event.pull_request.head.sha || '' }}

    - uses: $/.github/actions/setup-python

    - name: Install project dependencies
      shell: bash
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION_FOR_DUMMY_APP: ${{ needs.prep_env.outputs.app_version }}
      run: |
        pip install --root-user-action=ignore -e . --group test

    - name: Unit test with coverage
      env:
        RP_API_KEY: ${{ secrets.REPORTPORTAL_API_KEY }}
        AGENT_NO_ANALYTICS: True
      run: |
        pytest --junitxml=junit/test-results.xml \
          --log-cli-level DEBUG \
          --cov=dummy_app --cov-report=xml \
          --reportportal \
          --rp-launch "$GITHUB_REF_NAME" \
          --rp-launch-description "${GITHUB_EVENT_NAME}: $GITHUB_REF_NAME | $GITHUB_SHA" \
          -o "rp_tests_attributes=unit github $GITHUB_ACTOR" \
          -o "rp_launch_attributes=git_sha:${GITHUB_SHA}" \
          tests/unit/

    - name: Upload test results
      if: ${{ !env.ACT && always() }}
      uses: actions/upload-artifact@v7
      with:
        name: pytest-results
        path: junit/test-results.xml

    - name: Upload coverage results
      if: ${{ !env.ACT && always() }}
      uses: actions/upload-artifact@v7
      with:
        name: coverage-results
        path: coverage.xml
